import React from 'react'
import Head from "next/head";
import { Footer, Header, Layout } from '../components';
import "../globals.scss";

export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Squat2Fit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <link rel="icon" href="./" /> */}
      </Head>
      <Header />
      <Layout>
        <Component {...pageProps} />
      </Layout>
      <Footer />
    </>
  );
};